# Generated by Django 2.2.17 on 2021-01-27 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_newmodel"),
    ]

    operations = [
        migrations.DeleteModel(
            name="NewModel",
        ),
    ]
