# Generated by Django 2.2.17 on 2021-01-28 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_homepage_field2'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='field3',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
