# Generated by Django 2.2.17 on 2021-01-28 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_auto_20210127_1901"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="new_name",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
